name: Initial testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21.0.1'

      - name: Build and Test
        run: mvn -B package

      - name: Create Docs Directory
        run: mkdir -p docs/

      - name: Copy Surefire Reports
        run: cp -R target/surefire-reports/* docs/

      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: target/surefire-reports/
      
      - name: Commit and Push Reports
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add docs
          git commit -m "Update Test Reports [from workflow]"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleaning Up
        run: mvn clean
